import axios, { AxiosInstance } from 'axios';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Output parameters generated by the ML model
 */
interface OutputParams {
  title?: string;
  key: number;
  mode: number;
  bpm: number;
  energy: number;
  valence: number;
  chords: number[];
  melodies: number[][];
}

/**
 * Generation result with metadata
 */
interface GenerationResult {
  id: string;
  timestamp: string;
  type: 'api' | 'manual';
  params: OutputParams;
  filename: string;
}

/**
 * LoFi Generator that uses the server API
 */
class ApiLoFiGenerator {
  private apiClient: AxiosInstance;
  private outputDir: string;
  private manifestPath: string;
  private baseUrl: string;

  constructor(baseUrl: string = 'http://localhost:5000') {
    this.baseUrl = baseUrl;
    this.apiClient = axios.create({
      baseURL: baseUrl,
      timeout: 30000,
      headers: {
        'Access-Control-Allow-Origin': '*'
      }
    });
    
    this.outputDir = path.join(__dirname, '..', 'output');
    this.manifestPath = path.join(this.outputDir, 'manifest.json');
    
    // Create output directory if it doesn't exist
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  /**
   * Generate a random track using the server API
   */
  async generateRandom(filename?: string): Promise<GenerationResult> {
    try {
      console.log('Calling /generate API...');
      const response = await this.apiClient.get('/generate');
      
      // Parse the response (it comes as a JSON string)
      const params = typeof response.data === 'string' 
        ? JSON.parse(response.data) 
        : response.data;
      
      const result = this.saveGeneration('api', params, filename);
      console.log(`✓ Generated: ${result.filename}`);
      return result;
    } catch (error) {
      if (axios.isAxiosError(error)) {
        console.error('API Error:', error.message);
      } else {
        console.error('Error:', error);
      }
      throw error;
    }
  }

  /**
   * Generate a track from a latent vector using the server API
   */
  async decodeLatent(latent: number[], filename?: string): Promise<GenerationResult> {
    try {
      console.log('Calling /decode API with latent vector...');
      const response = await this.apiClient.get('/decode', {
        params: {
          input: JSON.stringify(latent)
        }
      });
      
      // Parse the response
      const params = typeof response.data === 'string' 
        ? JSON.parse(response.data) 
        : response.data;
      
      const result = this.saveGeneration('api', params, filename);
      console.log(`✓ Decoded: ${result.filename}`);
      return result;
    } catch (error) {
      if (axios.isAxiosError(error)) {
        console.error('API Error:', error.message);
      } else {
        console.error('Error:', error);
      }
      throw error;
    }
  }

  /**
   * Generate a track from lyrics using the server API
   */
  async predictFromLyrics(lyrics: string, filename?: string): Promise<GenerationResult> {
    try {
      console.log('Calling /predict API with lyrics...');
      const response = await this.apiClient.get('/predict', {
        params: {
          input: lyrics
        }
      });
      
      // Parse the response
      const params = typeof response.data === 'string' 
        ? JSON.parse(response.data) 
        : response.data;
      
      // Add title from lyrics if not present
      if (!params.title) {
        params.title = lyrics.substring(0, 50);
      }
      
      const result = this.saveGeneration('api', params, filename);
      console.log(`✓ Generated from lyrics: ${result.filename}`);
      return result;
    } catch (error) {
      if (axios.isAxiosError(error)) {
        console.error('API Error:', error.message);
      } else {
        console.error('Error:', error);
      }
      throw error;
    }
  }

  /**
   * Generate multiple random tracks
   */
  async generateBatch(count: number): Promise<GenerationResult[]> {
    const results: GenerationResult[] = [];
    for (let i = 0; i < count; i++) {
      console.log(`\nGenerating track ${i + 1}/${count}...`);
      try {
        const result = await this.generateRandom();
        results.push(result);
      } catch (error) {
        console.error(`Failed to generate track ${i + 1}`);
      }
    }
    return results;
  }

  /**
   * Check if server is running
   */
  async checkServer(): Promise<boolean> {
    try {
      const response = await this.apiClient.get('/', {
        timeout: 5000
      });
      return response.status === 200;
    } catch (error) {
      return false;
    }
  }

  /**
   * Save generation result to JSON file
   */
  private saveGeneration(
    type: 'api' | 'manual',
    params: OutputParams,
    filename?: string
  ): GenerationResult {
    const id = Math.random().toString(36).substring(7);
    const timestamp = new Date().toISOString();
    
    // Generate filename
    if (!filename) {
      filename = `lofi_${timestamp.replace(/[:.]/g, '-').substring(0, 19)}_${id}`;
    }
    
    // Clean filename
    filename = filename.replace(/[^a-zA-Z0-9_-]/g, '_');
    
    const result: GenerationResult = {
      id,
      timestamp,
      type,
      params,
      filename
    };
    
    // Save JSON file
    const filepath = path.join(this.outputDir, `${filename}.json`);
    fs.writeFileSync(filepath, JSON.stringify(result, null, 2));
    
    // Update manifest
    this.updateManifest(result);
    
    return result;
  }

  /**
   * Update the manifest file
   */
  private updateManifest(result: GenerationResult): void {
    let manifest = { tracks: [] as any[] };
    
    if (fs.existsSync(this.manifestPath)) {
      const content = fs.readFileSync(this.manifestPath, 'utf-8');
      manifest = JSON.parse(content);
    }
    
    manifest.tracks.push({
      id: result.id,
      filename: result.filename,
      timestamp: result.timestamp,
      type: result.type,
      title: result.params.title || 'Untitled',
      key: result.params.key,
      mode: result.params.mode,
      bpm: result.params.bpm,
      energy: result.params.energy,
      valence: result.params.valence
    });
    
    fs.writeFileSync(this.manifestPath, JSON.stringify(manifest, null, 2));
  }

  /**
   * List all generated tracks
   */
  listGenerated(): GenerationResult[] {
    const files = fs.readdirSync(this.outputDir).filter(f => f.endsWith('.json') && f !== 'manifest.json');
    return files.map(f => {
      const content = fs.readFileSync(path.join(this.outputDir, f), 'utf-8');
      return JSON.parse(content);
    });
  }

  /**
   * Get output directory path
   */
  getOutputDir(): string {
    return this.outputDir;
  }
}

/**
 * Command-line interface
 */
async function main() {
  const args = process.argv.slice(2);
  const command = args[0] || 'help';
  
  // Get server URL from env or use default
  const serverUrl = process.env.LOFI_SERVER_URL || 'http://localhost:5000';
  
  const generator = new ApiLoFiGenerator(serverUrl);
  
  try {
    // Check server
    console.log(`Checking server at ${serverUrl}...`);
    const serverRunning = await generator.checkServer();
    
    if (!serverRunning) {
      console.error(`✗ Server not running at ${serverUrl}`);
      console.error('Please start the server with: python server/app.py');
      process.exit(1);
    }
    console.log('✓ Server is running\n');
    
    // Process commands
    switch (command) {
      case 'single':
        await generator.generateRandom();
        break;
      
      case 'batch': {
        const count = parseInt(args[1]) || 10;
        console.log(`Generating ${count} tracks...`);
        await generator.generateBatch(count);
        break;
      }
      
      case 'lyrics': {
        const lyrics = args.slice(1).join(' ');
        if (!lyrics) {
          console.error('Please provide lyrics as arguments');
          process.exit(1);
        }
        await generator.predictFromLyrics(lyrics);
        break;
      }
      
      case 'decode': {
        const latentStr = args[1];
        if (!latentStr) {
          console.error('Please provide latent vector (comma-separated 100 values)');
          process.exit(1);
        }
        const latent = latentStr.split(',').map(x => parseFloat(x.trim()));
        if (latent.length !== 100) {
          console.error(`Expected 100 values, got ${latent.length}`);
          process.exit(1);
        }
        await generator.decodeLatent(latent);
        break;
      }
      
      case 'list': {
        const tracks = generator.listGenerated();
        console.log(`\nGenerated ${tracks.length} tracks:`);
        tracks.forEach((track, i) => {
          console.log(`${i + 1}. ${track.filename} - ${track.params.title || 'Untitled'}`);
        });
        break;
      }
      
      case 'help':
      default: {
        console.log(`
LoFi Music Generator - API Client

Usage: node dist/generator.js [command] [args]

Commands:
  single              Generate a single random track
  batch <count>       Generate N random tracks (default: 10)
  lyrics <text>       Generate track from lyrics
  decode <latent>     Generate track from latent vector (100 comma-separated values)
  list                List all generated tracks
  help                Show this help message

Environment:
  LOFI_SERVER_URL     Server URL (default: http://localhost:5000)

Examples:
  node dist/generator.js single
  node dist/generator.js batch 5
  node dist/generator.js lyrics "sad rainy day"
  node dist/generator.js list

Output directory: ${generator.getOutputDir()}
        `);
        break;
      }
    }
    
    console.log(`\n✓ Output saved to: ${generator.getOutputDir()}`);
  } catch (error) {
    console.error('Fatal error:', error);
    process.exit(1);
  }
}

main().catch(error => {
  console.error('Uncaught error:', error);
  process.exit(1);
});

export { ApiLoFiGenerator, GenerationResult };
